{% set version = "0.5.3dev" %}

package:
  name: tempita
  version: {{ version }}

source:
  fn: Tempita-{{ version }}dev.tar.gz
  url: https://pypi.io/packages/source/T/Tempita/Tempita-{{ version }}.tar.gz
  sha256: 38392bb708a10128419f75fa9120a6d2c8d137013b353968e5008a77a5c7a2ca
  patches:
    - remove-2to3.patch

build:
  noarch: python
  number: 1003
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - tempita

about:
  home: http://pypi.org/project/tempita
  license: MIT
  license_file: license.txt
  summary: A small templating language
  description: |
    tempita is a small templating language. This language implements
    if/elif/else, for/continue/break, expressions, and blocks of Python code.

extra:
  recipe-maintainers:
    - msarahan
