{% set version = "0.5.3dev" %}

package:
  name: tempita
  version: {{ version }}

source:
  fn: Tempita-{{ version }}dev.tar.gz
  url: https://pypi.io/packages/source/T/Tempita/Tempita-{{ version }}.tar.gz
  sha256: 38392bb708a10128419f75fa9120a6d2c8d137013b353968e5008a77a5c7a2ca
  patches:
    - except.patch
    - setup.patch

build:
  noarch: python
  number: 1004
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - tempita

about:
  home: http://pythonpaste.org/tempita/
  license: MIT
  license_file: LICENSE
  summary: A small templating language
  description: |
    tempita is a small templating language. This language implements
    if/elif/else, for/continue/break, expressions, and blocks of Python code.
  doc_url: http://pythonpaste.org/tempita/
  dev_url: https://bitbucket.org/ianb/tempita

extra:
  recipe-maintainers:
    - msarahan
    - jan-janssen
