appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KLBZm+GxJuo0q1DqIc/UAr2YyB6fLK74fQyp+ncu89TX9gXeXjl1fQ5/IophvNZ6syztbFaM2aZ2U6r7jJkFCq3mP3tNUaSCKCtvnKUPUNM0ZfvyhRqv1KiZNqY31oxNevQgpbq/UGmps38t4oVrBbxn3RHp1BrfLp9gIFE2swNktvBZDkruNkpbjy9EG+SA+76a98DHUUazo9H9cNNmQ5nQcKDLNR4745QqGPYlqkUcbdNx+5tBTEcl1NYNljDuYxSHLf9pfMhXHFF4rXQ4/ZOJTH9PWalrySKFzmAEeatrgUovRTJozPFITLdL51DbOwWNxVuqtGo4BWJIwmyksGmm7Aem3F74eO+fRWR/ZTrWwD03DaSVJgIqtYMfvnOEh40F7WUhTnlD5gqpICsqr1O0U6I+wsTPyfQLrAOM68UjkUrCFvdB54DbbMVazVcpGjUx04DNyrcNxEXaYDYm/iObzB+6U6kSZPO7weAO/EwQRsdE+HycBRc4DxvE/LqRXsZMl1/9kj4zdX7lVvv9E+SJA5lJeyB/SmbG8HrworQyHdvQEjNVc1Kp0baZqpHUUO8lIYKRdmx/35x4iJhSwCgxsf1iFd4z1BWZSWoqg5ax1oyqDARE0+h4WizStbigCv3TXl62CaMQVgQFI1OpLn/Z3UR/EYM+PyhaDCb0e6c=}
conda_forge_output_validation: false
